# Generated by Django 3.2.12 on 2022-04-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('razon', models.CharField(max_length=200)),
                ('escenafav', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('razon', models.CharField(max_length=200)),
                ('identificado', models.CharField(max_length=200)),
                ('escenafav', models.CharField(max_length=200)),
            ],
        ),
    ]
