# Generated by Django 3.2.12 on 2022-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='escenafav',
            new_name='escenafavp',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='nombre',
            new_name='nombrep',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='razon',
            new_name='razonp',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='nombre',
            new_name='pnombre',
        ),
        migrations.AlterField(
            model_name='informacion',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
